"""empty message

Revision ID: 1ea5bf847963
Revises: 8278b23652ff
Create Date: 2020-01-07 14:55:13.771946

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ea5bf847963'
down_revision = '8278b23652ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blend', sa.Column('blendlimit', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blend', 'blendlimit')
    # ### end Alembic commands ###
