"""empty message

Revision ID: 5150e546a2e6
Revises: 52f3e0164437
Create Date: 2020-01-05 10:40:27.791179

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5150e546a2e6'
down_revision = '52f3e0164437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blend_targets', sa.Column('targetlocation', sa.String(length=200), nullable=True))
    op.add_column('blend_targets', sa.Column('targetstate', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blend_targets', 'targetstate')
    op.drop_column('blend_targets', 'targetlocation')
    # ### end Alembic commands ###
