"""empty message

Revision ID: 52f3e0164437
Revises: 54a55ac1b353
Create Date: 2020-01-04 20:43:48.030731

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '52f3e0164437'
down_revision = '54a55ac1b353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blend', sa.Column('blenddate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blend', 'blenddate')
    # ### end Alembic commands ###
