"""empty message

Revision ID: 54a55ac1b353
Revises: 
Create Date: 2020-01-04 20:02:42.248709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54a55ac1b353'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blend',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('location', sa.String(length=200), nullable=False),
                    sa.Column('tankvolume', sa.String(length=200), nullable=True),
                    sa.Column('actualrvp', sa.String(length=200), nullable=False),
                    sa.Column('actualvl', sa.String(length=200), nullable=False),
                    sa.Column('actualt50', sa.String(length=200), nullable=True),
                    sa.Column('finalcalc', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('blend_targets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('targetdate', sa.DateTime(), nullable=True),
                    sa.Column('targetRVP', sa.String(length=200), nullable=True),
                    sa.Column('targetvl', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blend_targets')
    op.drop_table('blend')
    # ### end Alembic commands ###
