"""empty message

Revision ID: 6d9d2b029aa7
Revises: 171493b1fc94
Create Date: 2020-01-04 19:06:23.815340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6d9d2b029aa7'
down_revision = '171493b1fc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blend', sa.Column('targetrvp', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blend', 'targetrvp')
    # ### end Alembic commands ###
