"""empty message

Revision ID: 8278b23652ff
Revises: 
Create Date: 2020-01-07 12:06:36.721137

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8278b23652ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blend',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('location', sa.String(length=200), nullable=False),
                    sa.Column('tankvolume', sa.String(length=200), nullable=True),
                    sa.Column('actualrvp', sa.String(length=200), nullable=False),
                    sa.Column('actualvl', sa.String(length=200), nullable=True),
                    sa.Column('actualt50', sa.String(length=200), nullable=True),
                    sa.Column('finalcalc', sa.String(length=200), nullable=True),
                    sa.Column('blenddate', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blend')
    # ### end Alembic commands ###
